import { loopar, CoreInstaller, fileManage } from "loopar";
import sha1 from "sha1";
import crypto from "crypto";

/**
 * Generate a random URL-safe password.
 * Used when the tenant is auto-provisioned (no operator typing a password):
 * the customer recovers access via magic-link / password reset.
 */
function generateRandomPassword(length = 20) {
  return crypto.randomBytes(length).toString('base64url').slice(0, length);
}

export default class Installer extends CoreInstaller {
  module = "core";
  // Kept snake_case to match the column name in the App table.
  app_name = "loopar";

  /**
   * Auto-seed credentials from the tenant env when missing.
   * `CUSTOMER_EMAIL` is set by the control-plane provisioner so the first
   * Administrator is the paying customer, not a generic `admin`. Password is
   * random; customer recovers via email reset.
   */
  #seedFromEnv() {
    if (!this.email && process.env.CUSTOMER_EMAIL) {
      this.email = process.env.CUSTOMER_EMAIL;
    }
    if (!this.admin_password) {
      this.admin_password = generateRandomPassword();
      this.confirm_password = this.admin_password;
      this._autoGeneratedPassword = true;
    }
    if (!this.company && process.env.TENANT_ID) {
      this.company = process.env.TENANT_ID;
    }
  }

  async validate() {
    this.#seedFromEnv();

    if(this.admin_password !== this.confirm_password){
      loopar.throw("Passwords do not match");
    }

    /*if(this.admin_password.length < 8){
      loopar.throw("Password must be at least 8 characters long");
    }*/

    if(this.company.length < 3){
      loopar.throw("Company name must be at least 3 characters long");
    }

    if(this.email.length < 3){
      loopar.throw("Email must be at least 3 characters long");
    }

   /* if(this.admin_password === "admin"){
      loopar.throw("Password cannot be 'admin'");
    }

    if(this.email === "admin"){
      loopar.throw("Email cannot be 'admin'");
    }*/

    if(this.company === "admin"){
      loopar.throw("Company name cannot be 'admin'");
    }

    return await super.validate();
  }

  async install(reinstall = false) {
    if(reinstall) return super.install(true);
    await this.validate(reinstall);
    
    console.log("Installing Loopar");
    loopar.installingApp = "loopar";
    await this.setDbConfig();
    console.log("DB Config set");
    // alterSchema BEFORE initialize: when the autogenerated DB name doesn't
    // exist yet, the connector's MySQL retry path falls back to
    // information_schema and leaves `this.knex` pointing there. Subsequent
    // ALTER TABLE statements would then run against information_schema (no
    // permission). Creating the DB first via `coreConnection` (a separate
    // server-level handle that doesn't need a target DB) lets initialize(true)
    // connect straight to the new schema.
    await loopar.db.alterSchema();
    console.log("Schema Altered");
    await loopar.db.initialize(true);
    console.log("DB Initialized");
    await this.#makeCoreTable();
    console.log("Core Table Created");
    await super.install();
    return await this.insertAdministratorUser();
  }

  async insertAdministratorUser() {
    let user = null
    if (await loopar.db.getValue("User", 'name', "Administrator", { ifNotFound: false })){
      user = await loopar.getDocument("User", "Administrator");
    }else{
      user = await loopar.newDocument("User");
    }

    user.name = "Administrator";
    user.email = this.email;
    user.password = this.admin_password;
    user.confirm_password = this.confirm_password;
    user.__document_status__ = "Active";

    // When the password is auto-generated (cloud-provisioned tenant) we mark
    // the user so the desk can show a "set your password" banner and the
    // Profile can offer the email-reset shortcut. Recovery flow clears it.
    if (this._autoGeneratedPassword) {
      user.must_change_password = 1;
    }

    console.log(`Creating Administrator user for ${this.email}`);
    await user.save({ validate: false });
    console.log("Administrator user created");

    if (this._autoGeneratedPassword) {
      console.log(
        `[Installer] Password was auto-generated for ${this.email}. ` +
        `Customer should set their own via the magic-link or password-reset flow.`
      );
    }

    return true;
  }

  async setDbConfig() {
    const db_config = fileManage.getConfigFile('db.config');
    db_config.database = 'db_' + sha1(this.company + new Date().toISOString()).substring(0, 16);
    return await loopar.setDbConfig(db_config);
  }

  async #makeCoreTable() {
    const ref = loopar.getRef("Entity");
    const coreData = await this.getDocumentData("Entity", ref.__ROOT__);

    const Entity = await loopar.newDocument("Entity", coreData);
    await Entity.initialize({ validate: false });
  }
}