'use strict';

import BaseDocument from './base-document.js';
import { loopar } from '../loopar.js';

/**
 * BaseStorage — the shared parent class for every provider-specific
 * storage settings entity generated by `StorageBuilder`.
 *
 * Concrete subclasses (`Cloudinary Settings`, `Cloudflare R2 Settings`,
 * `Supabase Storage Settings`, …) extend this. The framework keeps the
 * generic behavior here so each provider's `.js` only has to declare
 * what's truly provider-specific: how to instantiate its driver from
 * the row's field values.
 *
 * Subclass contract:
 *   - **MUST** override `buildDriver()` to return a `StorageDriver`
 *     instance wired up with the row's fields. This is the only
 *     method the framework calls on the subclass when activating it.
 *
 * Shared behavior provided here:
 *   - `afterSave` / `afterDelete` hooks call `loopar.applyStorage()`
 *     so a credentials change or a flip in the active selection
 *     takes effect immediately, without a server restart.
 *   - `is_active` field semantics: the framework treats `0` as
 *     "disabled, fall back to the next-active or to local".
 *
 * The choice of *which* configured Storage Single is the active one
 * lives in `System Settings.active_storage` — `BaseStorage` does
 * not concern itself with selection.
 */
export default class BaseStorage extends BaseDocument {
  /**
   * Return a fully-configured `StorageDriver` instance for this
   * provider, using this row's field values.
   *
   * Concrete example for a Cloudinary Settings entity:
   *
   *   async buildDriver() {
   *     const { CloudinaryDriver } = await import(
   *       'loopar/core/global/storage/cloudinary-driver.js'
   *     );
   *     return new CloudinaryDriver({
   *       provider_id: this.cloud_name,
   *       access_key:  this.api_key,
   *       secret_key:  this.api_secret,
   *       folder_root: this.folder_root,
   *     });
   *   }
   *
   * Default throws — forces subclasses to implement.
   */
  async buildDriver() {
    throw new Error(
      `${this.__ENTITY__?.name || 'BaseStorage subclass'} must implement buildDriver().`
    );
  }

  /**
   * Re-apply the active storage configuration after every save.
   * `loopar.applyStorage()` re-reads the active integration from
   * `System Settings.active_storage` and re-builds the driver, so
   * changes propagate immediately to `loopar.storage.active`.
   */
  async afterSave() {
    if (typeof loopar.applyStorage === 'function') {
      await loopar.applyStorage();
    }
  }

  async afterDelete() {
    if (typeof loopar.applyStorage === 'function') {
      await loopar.applyStorage();
    }
  }
}
