
import { fileManage } from "../file-manage.js";
import fs from 'fs'
import path from "pathe";
import { fileURLToPath } from "url";
const tailwindClasses = {};
import { loopar } from "../loopar.js";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const getCss =  () => {
  try {
    return fs.readFileSync(path.resolve(__dirname, "./tailwind.css"), "utf8");
  } catch (err) {
    console.error("Unable to read tailwin base css", err);
  }
}

export async function setTailwindTemp(toElement, classes) {
  toElement && (tailwindClasses[toElement] = classes);
  let colector = "";

  const filterSpecialChars = (str) => {
    return str.replace(/[^a-zA-Z0-9:/ -]/g, '');
  };

  for (const [element, classes] of Object.entries(tailwindClasses)) {
    colector += `<div className="${filterSpecialChars(classes)}"/>`;
  }

  const fn = `
  export function Tailwind() {
    return (
      <div style={{display:"none"}}>${colector}</div>
    );
  }`

  await fileManage.makeFile('app/auto', 'tailwind', fn, 'jsx', true);
}

export async function generatedBaseCss(tenantId) {
  if(fs.existsSync(path.join(loopar.pathRoot, 'sites', tenantId, 'theme.css'))) {
    return;
  }

  await fileManage.makeFile(path.join('sites', tenantId), 'theme', getCss(), 'css');
}

/**
 * Generates app/auto/tailwind-apps.css with one @source per installed app.
 *
 * Why: /apps/* is gitignored (user content) and Tailwind's scanner (Oxide)
 * honors .gitignore even for glob @source patterns like
 * "../../../apps/**\/*.{tsx,jsx,json}" — those files were silently never
 * scanned. So utilities that only exist in app docs (e.g. a page's
 * doc_structure with image_height: "h-44", or classes typed in the designer's
 * `class` field) were missing from the compiled CSS in dev AND build: the
 * feature-card top panel collapsed to height 0 until the editor's Style tab
 * loaded the Tailwind browser JIT.
 *
 * Pointing @source at a concrete directory below the ignored boundary DOES
 * bypass the ignore (documented Tailwind behavior for ignored dirs), so we
 * emit one such line per app. Scoped to <app>/modules to avoid scanning
 * app-level node_modules/, uploads/ or .git/.
 */
export async function generateAppsTailwindSources() {
  const appsPath = path.join(loopar.pathRoot, "apps");

  const sources = !fs.existsSync(appsPath) ? [] :
    fs.readdirSync(appsPath, { withFileTypes: true })
      .filter(d => d.isDirectory() && !d.name.startsWith("."))
      .map(d => d.name)
      .filter(app => fs.existsSync(path.join(appsPath, app, "modules")))
      .sort()
      // Paths are relative to app/auto/, where this file is written.
      .map(app => `@source "../../apps/${app}/modules";`);

  const content = [
    "/* autogenerated by tailwinInit — do not edit by hand */",
    ...sources,
    "",
  ].join("\n");

  await fileManage.makeFile("app/auto", "tailwind-apps", content, "css", true);
}

export async function tailwinInit(tenantId) {
  await generatedBaseCss(tenantId);
  await generateAppsTailwindSources();
  await setTailwindTemp();
}