import { FormWrapper } from "@context/form-provider";
import { useRef, useState, useEffect } from "react";
import { Droppable } from "@droppable";
import { loopar } from "loopar";
import { Button } from "@cn/components/ui/button";
import { cn } from "@cn/lib/utils";
import { useDocument } from "@context/@/document-context";
import { buildFormData } from "@@tools/build-form-data";
import { useCaptcha, CaptchaSlot } from "./captcha-widget";

export default function MetaForm(props) {
  const formRef = useRef(null);
  const {
    title = "",
    document,
    action,
    action_text = "Submit",
    render_response,
    action_class,
    succes_message,
    error_message
  } = props.data;
  const [saved, setSaved] = useState(false);
  const [savedMessage, setSavedMessage] = useState(null);
  const [errorMessage, setErrorMessage] = useState(null);
  const [sending, setSending] = useState(false);
  const docCtx = useDocument();
  const { data = {} } = docCtx?.Document || {};

  // --- Anti-bot layer (same stack as the contact form) ----------------------
  const captcha = useCaptcha();
  const [hp, setHp] = useState("");
  const mountTsRef = useRef(null);
  useEffect(() => { mountTsRef.current = Date.now(); }, []);

  const submit = async () => {
    const api = formRef.current;
    if (!api) return;
    const submited = await api.submit();

    if (!submited) return;
    if (!captcha.ready) return;

    setSending(true);
    setErrorMessage(null);

    try {
      if (document && action) {
        // Custom pipeline: the designer pointed this form at its own
        // controller/action (e.g. an entity generated by the Contact Form
        // Builder, whose inherited submit expects the anti-bot fields too).
        const fd = buildFormData(submited);
        fd.append("captcha_token", captcha.token || "");
        fd.append("_hp", hp);
        fd.append("_elapsed", String(Date.now() - (mountTsRef.current || Date.now())));

        const res = await loopar.call(document, action, { body: fd });
        setSavedMessage(res?.message || succes_message || "Submitted successfully");
      } else {
        // Generic pipeline: the PAGE receives the submit and validates
        // against its own metadata (the same definition that rendered this
        // form), scoped to this form via node/form_name. Storage lands in
        // the Form Submission entity server-side.
        const res = await loopar.call(docCtx?.name, "submitForm", {
          body: {
            ...submited,
            node: props.node,
            form_name: props.data?.name,
            captcha_token: captcha.token,
            _hp: hp,
            _elapsed: Date.now() - (mountTsRef.current || Date.now())
          }
        });
        setSavedMessage(res?.message || succes_message || "Submitted successfully");
      }
      setSaved(true);
      // Blank the fields so the form is ready for another submission
      // (formRef api → react-hook-form reset with explicit empty values).
      formRef.current?.clear?.();
    } catch (e) {
      setErrorMessage(e?.message || error_message || "Something went wrong. Please try again.");
    } finally {
      setSending(false);
      captcha.reset();
    }
  };

  if (render_response && saved && savedMessage) {
    return <p>{String(savedMessage)}</p>;
  }

  return (
    <FormWrapper
      STRUCTURE={props.elements}
      __DATA__={data}
      className="w-full"
      formRef={formRef}
    >
      <div className="w-full border">
        <div className="p-4">
          <p className="text-md font-medium tracking-widest uppercase text-muted-foreground">
            {title}
          </p>

          <div className="p-2">
            <Droppable {...props} />
          </div>

          {/* Honeypot — visually removed, invisible to humans, bait for bots */}
          <div
            aria-hidden="true"
            style={{ position: "absolute", left: "-9999px", top: "auto", width: "1px", height: "1px", overflow: "hidden" }}
          >
            <label htmlFor={`form_hp_${props.node || "x"}`}>Website</label>
            <input
              id={`form_hp_${props.node || "x"}`}
              type="text"
              name="website"
              tabIndex={-1}
              autoComplete="off"
              value={hp}
              onChange={(e) => setHp(e.target.value)}
            />
          </div>

          <CaptchaSlot captcha={captcha} />

          {errorMessage && (
            <p className="text-sm text-destructive pt-2">{String(errorMessage)}</p>
          )}

          <div className={cn(
            "flex justify-end gap-2 pt-4",
            "border-t border-border/40"
          )}>
            <Button
              type="button"
              size="sm"
              onClick={submit}
              disabled={sending || !captcha.ready}
              className={action_class}
            >
              {sending ? "Sending..." : action_text}
            </Button>
          </div>
        </div>
      </div>
    </FormWrapper>
  );
}

MetaForm.metaFields = () => [{
  group: "form",
  elements: {
    title: { element: INPUT },
    document: {
      element: INPUT,
      data: { description: "Optional: target Document for a custom action. Leave empty to use the generic Form Submission pipeline (server-side validation from this form's own fields)." }
    },
    action: {
      element: INPUT,
      data: { description: "Optional: custom controller action. Leave empty for the generic pipeline." }
    },
    action_text: { element: INPUT },
    action_class: { element: INPUT },
    render_response: { element: SWITCH },
    succes_message: { element: TEXTAREA },
    error_message: { element: TEXTAREA },
    notify: {
      element: SWITCH,
      data: { label: "Notify by Email", description: "Send an email (Email Settings recipient, or the address below) on every submission of this form." }
    },
    notify_email: {
      element: INPUT,
      data: { label: "Notify Email", description: "Overrides the recipient for this form's notifications." }
    }
  }
}];
